### ISSUE TITLE
Fix CI builds

### ISSUE THREAD

**Issue by mpyw** [mpyw/axios-case-converter#35]
https://github.com/mpyw/axios-case-converter/pull/34#issuecomment-760158447

**Comment by davidfishlock** [comment]
@mpyw what do you think is the best approach here? In the short term we can amend the travis config to only run on `lts` but this isn't addressing the root cause of the exceptions in the test run on Node 15.

If the problem is related to the Travis environment a possible solution could be to move the CI over to github actions.

**Comment by davidfishlock** [comment]
Have resolved this here: https://github.com/mpyw/axios-case-converter/pull/36
