### ISSUE TITLE
camel case converter is not following the default rules.

### ISSUE THREAD

**Issue by j0eii** [mpyw/axios-case-converter#44]
main code:

```
    camel: (input, options) => {
      return (input.charAt(0).toLowerCase() + input.slice(1)).replace(/[-_](.)/g, (match, group1) => group1.toUpperCase());
    }

=>

input : pub_pub_256 
return: pubPub256
```

however, when deployed with axios, it will return pubPub_256, instead of pubPub256.

Current work around is prepadding a char before numeric.

**Comment by mpyw** [comment]
Hi! This issue is caused by the library internally used by `axios-case-converter`.

- [change-case/packages/camel-case at master · blakeembrey/change-case](https://github.com/blakeembrey/change-case/tree/master/packages/camel-case)

And the related PR:

- [ADDED Option to separate numbers in snake Case by aayush123 · Pull Request #215 · blakeembrey/change-case](https://github.com/blakeembrey/change-case/pull/215)
